In [13]:
import pandas as pd
from sqlalchemy import create_engine
from config import username, password

In [14]:
csv_county = "Data/county_data_2017.csv"
county_df = pd.read_csv(csv_county)
county_df.head()

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,...,0.6,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2
1,1003,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,...,0.8,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5
2,1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,...,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4
3,1007,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,...,0.3,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2
4,1009,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,...,0.4,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9

In [15]:
county_df = county_df[['State', 'County', 'TotalPop', 'Income', 'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty', 'Unemployment']].copy()
county_df = county_df.rename(columns = {'State':'state', 'County':'county', 'TotalPop':'total_pop', 
                            'Income':'income', 'IncomeErr':'income_err', 'IncomePerCap':'income_per_cap', 
                            'IncomePerCapErr':'income_per_cap_err', 'Poverty':'poverty', 'Unemployment':'unemployment'}).copy()
county_df.head()

,state,county,total_pop,income,income_err,income_per_cap,income_per_cap_err,poverty,unemployment
0,Alabama,Autauga County,55036,55317,2838,27824,2024,13.7,5.2
1,Alabama,Baldwin County,203360,52562,1348,29364,735,11.8,5.5
2,Alabama,Barbour County,26201,33368,2551,17561,798,27.2,12.4
3,Alabama,Bibb County,22580,43404,3431,20911,1889,15.2,8.2
4,Alabama,Blount County,57667,47412,2630,22021,850,15.6,4.9

In [16]:
csv_vaccine = "Data/Vaccine_Hesitancy.csv"
vaccine_df = pd.read_csv(csv_vaccine)
vaccine_df.head()

,FIPS Code,County Name,State,Estimated hesitant,Estimated strongly hesitant,Social Vulnerability Index (SVI),SVI Category,CVAC level of concern for vaccination rollout,CVAC Level Of Concern,Percent adults fully vaccinated against COVID-19,Percent Hispanic,Percent non-Hispanic American Indian/Alaska Native,Percent non-Hispanic Asian,Percent non-Hispanic Black,Percent non-Hispanic Native Hawaiian/Pacific Islander,Percent non-Hispanic White,Geographical Point,State Code,County Boundary,State Boundary
0,1131,"Wilcox County, Alabama",ALABAMA,0.23,0.11,0.93,Very High Concern,0.94,Very High Concern,0.228,0.0053,0.0009,0.0003,0.6938,0.0000,0.2684,POINT (-86.844516 32.756889),AL,"MULTIPOLYGON (((-87.52534299999999 32.132773, ...","MULTIPOLYGON (((-88.139988 34.581703, -88.1352..."
1,1129,"Washington County, Alabama",ALABAMA,0.23,0.11,0.73,High Concern,0.82,Very High Concern,0.192,0.0146,0.0731,0.0025,0.2354,0.0000,0.6495,POINT (-86.844516 32.756889),AL,"MULTIPOLYGON (((-88.45317899999999 31.505388, ...","MULTIPOLYGON (((-88.139988 34.581703, -88.1352..."
2,1133,"Winston County, Alabama",ALABAMA,0.22,0.11,0.70,High Concern,0.80,High Concern,0.085,0.0315,0.0034,0.0016,0.0073,0.0005,0.9370,POINT (-86.844516 32.756889),AL,"MULTIPOLYGON (((-87.63656399999999 34.120908, ...","MULTIPOLYGON (((-88.139988 34.581703, -88.1352..."
3,1127,"Walker County, Alabama",ALABAMA,0.23,0.11,0.75,High Concern,0.68,High Concern,0.158,0.0249,0.0015,0.0049,0.0617,0.0000,0.8895,POINT (-86.844516 32.756889),AL,"MULTIPOLYGON (((-87.56108499999999 33.868713, ...","MULTIPOLYGON (((-88.139988 34.581703, -88.1352..."
4,2013,"Aleutians East Borough, Alaska",ALASKA,0.26,0.12,0.58,Moderate Concern,0.87,Very High Concern,0.195,0.0901,0.4588,0.1968,0.0322,0.0100,0.1321,POINT (-151.631889 63.631126),AK,"MULTIPOLYGON (((-165.036163 54.576598, -165.01...","MULTIPOLYGON (((-165.254162 60.917108, -165.30..."

In [17]:
vaccine_df['County Name'] = vaccine_df["County Name"].str.split(",", n = 1, expand = True)

vaccine_df = vaccine_df[['County Name', 'State', 'Estimated hesitant',
       'Estimated strongly hesitant', 'Social Vulnerability Index (SVI)',
       'CVAC level of concern for vaccination rollout',
       'Percent adults fully vaccinated against COVID-19']].copy()
vaccine_df = vaccine_df.rename(columns = {'County Name':'county_name', 'State':'state', 'Estimated hesitant':'est_hesitant',
       'Estimated strongly hesitant': 'est_strongly_hesitant', 'Social Vulnerability Index (SVI)': 'svi',
       'CVAC level of concern for vaccination rollout': 'cvac_level_of_concern_rollout',
       'Percent adults fully vaccinated against COVID-19':'percent_adults_fully_vaccinated'}).copy()

vaccine_df['state'] = vaccine_df['state'].str.title().copy()

vaccine_df.head()

,county_name,state,est_hesitant,est_strongly_hesitant,svi,cvac_level_of_concern_rollout,percent_adults_fully_vaccinated
0,Wilcox County,Alabama,0.23,0.11,0.93,0.94,0.228
1,Washington County,Alabama,0.23,0.11,0.73,0.82,0.192
2,Winston County,Alabama,0.22,0.11,0.70,0.80,0.085
3,Walker County,Alabama,0.23,0.11,0.75,0.68,0.158
4,Aleutians East Borough,Alaska,0.26,0.12,0.58,0.87,0.195

In [18]:
#  Connect to local database

rds_connection_string = f"{username}:{password}@localhost:5432/Project2"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [19]:
engine.table_names()

<ipython-input-19-8f1edc7208d0>:1: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  engine.table_names()

['census_vaccine_data', 'vaccine_data', 'census_data']

In [20]:
# Use pandas to load csv converted DataFrame into database for census data
county_df.to_sql(name='census_data', con=engine, if_exists='append', index=False)

In [30]:
# Use pandas to load csv converted DataFrame into database for vaccine hesitancy data
vaccine_df.to_sql(name='vaccine_data', con=engine, if_exists='append', index=False)

In [21]:
# Display final table
pd.read_sql_query('SELECT * FROM census_vaccine_data', con=engine)

,state,county,total_pop,income,income_err,income_per_cap,income_per_cap_err,poverty,unemployment,est_hesitant,est_strongly_hesitant,svi,cvac_level_of_concern_rollout,percent_adults_fully_vaccinated
0,South Carolina,Abbeville County,24788,35254,2259.0,19234,799,22.7,9.4,0.19,0.09,0.86,0.81,0.199
1,Louisiana,Acadia Parish,62607,40492,2544.0,21591,1002,21.5,8.9,0.24,0.11,0.92,0.72,0.177
2,Virginia,Accomack County,32840,42260,2253.0,24266,1564,19.8,5.4,0.15,0.06,0.80,0.50,0.269
3,Idaho,Ada County,435117,60151,1294.0,31642,725,11.8,4.3,0.24,0.11,0.14,0.13,0.259
4,Iowa,Adair County,7192,49477,2633.0,28861,2055,9.5,3.0,0.21,0.11,0.05,0.01,0.205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3135,Arizona,Yuma County,204281,43253,1376.0,20600,428,19.7,10.9,0.19,0.12,0.99,0.96,0.174
3136,Colorado,Yuma County,10109,44668,2373.0,24789,1902,14.3,2.4,0.19,0.08,0.56,0.47,0.061
3137,Texas,Zapata County,14415,34550,6700.0,17817,3167,34.1,12.4,0.18,0.09,0.99,1.00,NaN
3138,Texas,Zavala County,12152,25988,5009.0,13105,1562,36.2,10.1,0.17,0.09,1.00,1.00,NaN
3139,South Dakota,Ziebach County,2837,35000,4262.0,13461,1017,43.1,27.0,0.29,0.12,0.95,0.82,0.122